//
// ExportPatterns.swift
// HapticEngine
//
// Writes the Android library's patterns, and the Android demo's descriptions of them, from the iOS ones,
// so the two platforms play the same patterns and the demos describe them alike. Run
// `Android/scripts/export-patterns.sh` from the repository root, which builds this with the iOS library
// and the iOS demo's descriptions, then commit what it writes.
//
// The iOS library is the source of truth: its patterns are built by hand or generated by
// `iOS/Scripts/GeneratePatterns.swift`. This only copies them, rounded to what Android can play: times to
// the millisecond and levels to a thousandth, finer than any vibrator can tell apart.
//

import Foundation
import HapticEngine
import SwiftUI

@main
struct ExportPatterns {
    static let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)

    static func main() throws {
        let patterns = HapticPattern.allCases
        try writeEnum(patterns)
        try writeEvents(patterns)
        try writeDemoCatalog(patterns)
        print("Exported \(patterns.count) patterns to Android.")
    }

    // MARK: Library: the enum

    /// The iOS case's name as an enum entry: `heavyMetalHit` becomes `HeavyMetalHit`, as `success` became `Success`.
    static func entryName(_ pattern: HapticPattern) -> String {
        pattern.rawValue.prefix(1).uppercased() + pattern.rawValue.dropFirst()
    }

    /// Fills in the generated part of `HapticPattern.kt`: every pattern after the first ten, documented and
    /// grouped as in `HapticPattern.swift`.
    static func writeEnum(_ patterns: [HapticPattern]) throws {
        let swift = try String(contentsOf: root.appending(path: "iOS/Sources/HapticEngine/HapticPattern.swift"), encoding: .utf8)
        var docs: [String: [String]] = [:]
        var marks: [String: String] = [:]
        var pendingDoc: [String] = []
        var pendingMark: String?
        for line in swift.split(separator: "\n", omittingEmptySubsequences: false) {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.hasPrefix("// MARK: ") {
                pendingMark = String(trimmed.dropFirst("// MARK: ".count))
            } else if trimmed.hasPrefix("///") {
                pendingDoc.append(String(trimmed.dropFirst(3)).trimmingCharacters(in: .whitespaces))
            } else if trimmed.hasPrefix("case ") {
                let name = String(trimmed.dropFirst("case ".count))
                docs[name] = pendingDoc
                if let pendingMark { marks[name] = pendingMark }
                pendingDoc = []
                pendingMark = nil
            } else if !trimmed.isEmpty {
                pendingDoc = []
            }
        }

        var entries: [String] = []
        for pattern in patterns.dropFirst(sharedCount) {
            var lines: [String] = []
            if let mark = marks[pattern.rawValue] {
                lines.append("    // \(mark)")
                lines.append("")
            }
            let doc = (docs[pattern.rawValue] ?? []).map(kdoc)
            if doc.count == 1 {
                lines.append("    /** \(doc[0]) */")
            } else if !doc.isEmpty {
                lines.append("    /**")
                lines += doc.map { $0.isEmpty ? "     *" : "     * \($0)" }
                lines.append("     */")
            }
            lines.append("    \(entryName(pattern)),")
            entries.append(lines.joined(separator: "\n"))
        }
        // The last entry ends the list.
        var body = entries.joined(separator: "\n\n")
        body.removeLast()
        body += ";"

        let file = root.appending(path: "Android/hapticengine/src/main/kotlin/dev/codepassion/hapticengine/HapticPattern.kt")
        let kotlin = try String(contentsOf: file, encoding: .utf8)
        let begin = "    // BEGIN GENERATED PATTERNS"
        let end = "    // END GENERATED PATTERNS"
        guard let start = kotlin.range(of: begin), let stop = kotlin.range(of: end) else {
            throw ExportError("HapticPattern.kt has no generated section")
        }
        let header = kotlin[start.lowerBound...].prefix { $0 != "\n" }
        let updated = kotlin[..<start.lowerBound] + header + "\n\n" + body + "\n" + kotlin[stop.lowerBound...]
        try write(String(updated), to: file)
    }

    /// The patterns shared with Android since 1.0, whose entries and documentation are written by hand.
    static let sharedCount = 10

    /// A Swift doc comment line as KDoc: ``heavyMetalHit`` links become [HeavyMetalHit].
    static func kdoc(_ line: String) -> String {
        var result = ""
        var rest = Substring(line)
        while let open = rest.range(of: "``") {
            result += rest[..<open.lowerBound]
            let after = rest[open.upperBound...]
            guard let close = after.range(of: "``") else {
                result += rest[open.lowerBound...]
                rest = ""
                break
            }
            let symbol = String(after[..<close.lowerBound])
            if let pattern = HapticPattern(rawValue: symbol) {
                result += "[\(entryName(pattern))]"
            } else {
                result += "`\(symbol)`"
            }
            rest = after[close.upperBound...]
        }
        return (result + rest).replacingOccurrences(of: "*/", with: "* /")
    }

    // MARK: Library: the events

    /// Every pattern's events as text, in entry order: see `HapticPatternData.kt`. Split into chunks, as one
    /// array of four thousand strings is more than a JVM method can hold.
    static func writeEvents(_ patterns: [HapticPattern]) throws {
        let encoded = patterns.map(encode)
        let chunkSize = 500
        var chunks: [String] = []
        for start in stride(from: 0, to: encoded.count, by: chunkSize) {
            let rows = encoded[start..<min(start + chunkSize, encoded.count)].map { "        \"\($0)\"," }
            chunks.append("""
                private object HapticPatternData\(chunks.count) {
                    val encoded: Array<String> = arrayOf(
                \(rows.joined(separator: "\n"))
                    )
                }
                """)
        }
        let lookups = (0..<chunks.count).map { "            \($0) -> HapticPatternData\($0).encoded[offset]" }
        let kotlin = """
            // Written by Android/scripts/export-patterns.sh from the iOS patterns. Don't edit by hand.

            package dev.codepassion.hapticengine

            /**
             * Every pattern's events, copied from the iOS library so both platforms play the same patterns.
             *
             * Each pattern is text, events separated by `;`: a tap as `t,timeMs,intensity,sharpness` and a hold as
             * `h,timeMs,durationMs,intensity,sharpness`, with levels in thousandths. Text rather than thousands of
             * nested constructors, which made the compiler crawl and the class too large to load.
             */
            internal object HapticPatternData {
                const val COUNT: Int = \(encoded.count)
                private const val CHUNK_SIZE = \(chunkSize)

                /** The encoded events of the pattern at [ordinal]. */
                fun encoded(ordinal: Int): String {
                    val offset = ordinal % CHUNK_SIZE
                    return when (ordinal / CHUNK_SIZE) {
            \(lookups.joined(separator: "\n"))
                        else -> throw IndexOutOfBoundsException("No pattern at $ordinal")
                    }
                }
            }

            \(chunks.joined(separator: "\n\n"))

            """
        try write(kotlin, to: root.appending(path: "Android/hapticengine/src/main/kotlin/dev/codepassion/hapticengine/HapticPatternData.kt"))
    }

    static func encode(_ pattern: HapticPattern) -> String {
        let events = pattern.events
        return events.enumerated().map { index, event in
            let start = milliseconds(event.time)
            let level = { (value: Float) in Int((Double(value) * 1000).rounded()) }
            switch event.kind {
            case .tap:
                return "t,\(start),\(level(event.intensity)),\(level(event.sharpness))"
            case .hold:
                // From the rounded start and end, so back-to-back holds still meet. Where rounding a time
                // that falls on half a millisecond would have one run a millisecond into the next, it stops
                // where the next starts, as it does on iOS.
                var end = milliseconds(event.time + event.duration)
                if let next = events.dropFirst(index + 1).first(where: { $0.kind == .hold }) {
                    end = min(end, milliseconds(next.time))
                }
                return "h,\(start),\(end - start),\(level(event.intensity)),\(level(event.sharpness))"
            }
        }.joined(separator: ";")
    }

    static func milliseconds(_ seconds: TimeInterval) -> Int {
        Int((seconds * 1000).rounded())
    }

    // MARK: Demo: names, descriptions, icons and categories

    static func writeDemoCatalog(_ patterns: [HapticPattern]) throws {
        let categories = HapticPattern.Category.allCases
        let categoryEntries = categories.map { category in
            let tint = namedColors.first { $0.1 == category.tint }?.0 ?? "Gray"
            let group = HapticPattern.Category.handWritten.contains(category) ? "BuiltIn" : "Families"
            return "    \(entryName(category))(\"\(category.title)\", \"\(category.systemImage)\", DemoTint.\(tint), CategoryGroup.\(group)),"
        }
        let chunkSize = 1000
        var chunks: [String] = []
        for start in stride(from: 0, to: patterns.count, by: chunkSize) {
            let rows = patterns[start..<min(start + chunkSize, patterns.count)].map { pattern in
                let fields = [pattern.title, pattern.subtitle, pattern.systemImage, String(categories.firstIndex(of: pattern.category)!)]
                return "        \"\(fields.map(escape).joined(separator: "|"))\","
            }
            chunks.append("""
                private object PatternDetailsData\(chunks.count) {
                    val rows: Array<String> = arrayOf(
                \(rows.joined(separator: "\n"))
                    )
                }
                """)
        }
        let lookups = (0..<chunks.count).map { "            \($0) -> PatternDetailsData\($0).rows[offset]" }
        let symbols = Set(patterns.map(\.systemImage) + categories.map(\.systemImage)).sorted()
        let kotlin = """
            // Written by Android/scripts/export-patterns.sh from the iOS demo. Don't edit by hand.

            package dev.codepassion.hapticengine.demo

            /**
             * The categories the demo groups patterns under, as in the iOS demo: the seven groups of patterns built
             * by hand, then the families. The name is saved, so renaming one forgets a saved filter for it.
             */
            enum class PatternCategory(val title: String, val symbol: String, val tint: DemoTint, val group: CategoryGroup) {
            \(categoryEntries.joined(separator: "\n").dropLast());
            }

            /**
             * Each pattern's name, description, symbol and category, by ordinal, from the iOS demo. Each row is
             * `title|subtitle|symbol|category ordinal`. Symbols are SF Symbols names, drawn with the Material icon
             * `PatternSymbols.kt` maps each to.
             */
            internal object PatternDetailsData {
                private const val CHUNK_SIZE = \(chunkSize)

                /** Every symbol a pattern or category uses, so a test can check each has an icon. */
                val symbols: List<String> = listOf(
            \(symbols.map { "        \"\($0)\"," }.joined(separator: "\n"))
                )

                fun row(ordinal: Int): String {
                    val offset = ordinal % CHUNK_SIZE
                    return when (ordinal / CHUNK_SIZE) {
            \(lookups.joined(separator: "\n"))
                        else -> throw IndexOutOfBoundsException("No pattern at $ordinal")
                    }
                }
            }

            \(chunks.joined(separator: "\n\n"))

            """
        try write(kotlin, to: root.appending(path: "Android/example/src/main/kotlin/dev/codepassion/hapticengine/demo/PatternDetailsData.kt"))
    }

    static func entryName(_ category: HapticPattern.Category) -> String {
        category.rawValue.prefix(1).uppercased() + category.rawValue.dropFirst()
    }

    /// The system colors the iOS demo tints with, by the name `DemoTint` gives each.
    static let namedColors: [(String, Color)] = [
        ("Blue", .blue), ("Indigo", .indigo), ("Teal", .teal), ("Green", .green), ("Orange", .orange),
        ("Red", .red), ("Pink", .pink), ("Brown", .brown), ("Purple", .purple), ("Cyan", .cyan),
        ("Mint", .mint), ("Gray", .gray), ("Yellow", .yellow),
    ]

    static func escape(_ field: String) -> String {
        precondition(!field.contains("|"), "\(field) contains the field separator")
        return field.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "$", with: "\\$")
    }

    static func write(_ text: String, to url: URL) throws {
        try text.write(to: url, atomically: true, encoding: .utf8)
    }
}

struct ExportError: Error, CustomStringConvertible {
    let description: String
    init(_ description: String) { self.description = description }
}
